Vagrant.configure("2") do |config|
  #Server machine
  config.vm.define "hcharefs" do |sconfig|
    sconfig.vm.box = "ubuntu/focal64"
#configure memory and cpu
    sconfig.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
    sconfig.vm.hostname = "hcharefS"
    sconfig.vm.network "private_network", ip: "192.168.56.110"
    config.vm.synced_folder "./confs", "/home/vagrant/confs"
    sconfig.vm.provision "shell", path: "scripts/script.sh"
  end
end
