#define the configuration file version
#do represents a CHUNK of code starting with do and ending 
#with end 
Vagrant.configure("2") do |config|
  #Server machine
  config.vm.define "hcharefs" do |sconfig|
    sconfig.vm.box = "generic/debian12"
#configure memory and cpu
    sconfig.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    sconfig.vm.hostname = "hcharefS"
    sconfig.vm.network "private_network", ip: "192.168.56.110"
    sconfig.vm.provision "shell", inline:  <<-SHELL
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get install -y curl
      #install k3s server
      curl -sfL https://get.k3s.io | sh - 
      #find the token and put it in the shared folder so we can access to it from the worker machine 
      cat /var/lib/rancher/k3s/server/node-token > /vagrant/token.txt

    SHELL
    

  end
  #Client machine
  config.vm.define "hcharefsw" do |cconfig|
    cconfig.vm.box = "generic/debian12"
    cconfig.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end
    cconfig.vm.hostname = "hcharefSW"
    cconfig.vm.network "private_network", ip: "192.168.56.111"
    cconfig.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get install -y curl
      sleep 5
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=\$(cat /vagrant/token.txt) sh -
      #install k3s agent after getting server's token
    SHELL

  end



